sudo: required
services:
  - docker

before_install:
  - docker build -t camposped/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true camposped/react-test npm test

after_success:
  - docker build -t camposped/multi-client ./client
  - docker build -t camposped/multi-nginx ./nginx
  - docker build -t camposped/multi-server ./server
  - docker build -t camposped/multi-worker ./worker

deploy:
  - 